FROM registry.access.redhat.com/ubi8/nodejs-20-minimal as builder

USER 0
ADD ./ /tmp/src
RUN chown -R 1001:0 /tmp/src

USER 1001

RUN /usr/libexec/s2i/assemble

FROM ubi8/nodejs-20-minimal

COPY --from=builder $HOME $HOME

#Expose server at port ( accessible outside of container)
EXPOSE 8080

#Start app
CMD /usr/libexec/s2i/run